### ISSUE TITLE
[Doc] Check failed to raise error in "Enriching your warehouse" tutorial

### ISSUE THREAD

**Issue by christeefy** [sdf-labs/sdf-cli#10]
**Describe the bug**
I'm going through the tutorials so far. Currently at the "[Enriching your warehouse](https://docs.sdf.com/tutorials/enriching-your-warehouse)" tutorial and everything is working as expected until Step 6 ("Set Up Guardrails"). 

The check did not raise an error despite the `moms_flower_shop.staging.app_installs.event_id` being classified as both `EVENT.in_app` and `EVENT.marketing`. 

**To Reproduce**
1. Go to the [tutorial](https://docs.sdf.com/tutorials/enriching-your-warehouse)
2. Run until Step 6
3. Copy the SQL file
4. Run `sdf check mixed_event_ids --show result`

**Expected behavior**

An error should be raised, but I got `[Pass] Check moms_flower_shop.pub.mixed_event_ids` instead

**Screenshots**

![image](https://github.com/user-attachments/assets/fca0c02a-6ec0-4f61-b13f-e84c340d170e)

**Comment by eliasdefaria** [comment]
Thanks for your report @christeefy! This has been fixed in the latest version of SDF. Fixed confirmed on [v0.10.0-p](https://github.com/sdf-labs/sdf-cli/releases/tag/v0.10.1-p).
