### ISSUE TITLE
Support INITCAP function

### ISSUE THREAD

**Issue by dbartley2-wiq** [sdf-labs/sdf-cli#13]
**Summarize the feature in question.**
Please add support for the INITCAP function.

https://docs.snowflake.com/en/sql-reference/functions/initcap
https://learn.microsoft.com/en-us/azure/databricks/sql/language-manual/functions/initcap
https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#initcap

**Comment by dbrtly** [comment]
Am happy to close this as fixed now
