### ISSUE TITLE
Docs: Slack invitation link broken

### ISSUE THREAD

**Issue by c-thiel** [sdf-labs/sdf-cli#14]
There is a Slack invitation Link in the docs that is broken: https://docs.sdf.com/introduction/getting-started
(https://join.slack.com/t/sdfcommunity/shared_invite/zt&#45;2lkokt7ed&#45;xIR0_pcmUOU3~CebxuqeKg)

I hope this is an OK place to report this?

**Comment by eliasdefaria** [comment]
Thanks for the report @c-thiel! This has been fixed in the latest. In fact, we created a fancy mini link with our three letter domain: https://sdf.com/join
