### ISSUE TITLE
Auto complete

### ISSUE THREAD

**Issue by dbrtly** [sdf-labs/sdf-cli#16]
**Summarize the feature in question.**
![image](https://github.com/user-attachments/assets/e1b2e84e-b7bb-43ad-a842-2f8c078642c0)
![image](https://github.com/user-attachments/assets/113da1d1-2678-4df0-95a5-cd1673733163)

**What team(s) will benefit from this feature request?**
All users of the cli tool

**Is this an enhancement to an existing feature? If so, briefly describe the update.**
Enhances the existing cli tool

**Describe alternatives you've considered if applicable.**
Mash keys like an animal

**Additional context**
Quick googling suggests clap_complete is the crate to use. 

https://docs.rs/clap_complete

I'm interested in contributing.

**Comment by eliasdefaria** [comment]
Hahaha the memes are so good. I'm going to mark this as a dup of https://github.com/sdf-labs/sdf-cli/issues/19
