### ISSUE TITLE
Installer doesn't work with some arm64 platforms

### ISSUE THREAD

**Issue by kalona** [sdf-labs/sdf-cli#18]
**Describe the bug**
This fails on some arm64 platforms:
curl -LSfs https://cdn.sdf.com/releases/download/install.sh | sh -s

**To Reproduce**
curl -LSfs https://cdn.sdf.com/releases/download/install.sh | sh -s

![image](https://github.com/user-attachments/assets/11048833-b65d-4f32-a288-145a8ccf4aa8)

**Additional context**
The issue is when this command returns something different than expected in the install.sh:
   if [ "$cpu_arch_target" = "arm64" ]; then
                target="aarch64-unknown-linux-gnu"

❯ uname -m
aarch64

The solution could be to add one more condition to the if statement:

   if [ "$cpu_arch_target" = "arm64" ] || [ "$cpu_arch_target" = "aarch64" ]; then
                target="aarch64-unknown-linux-gnu"

![image](https://github.com/user-attachments/assets/6781c558-3cf6-4082-b065-664165fa860e)

**Comment by eliasdefaria** [comment]
Thanks @kalona! Fix for this will be out in the next preview release

**Comment by venkaa28** [comment]
@kalona the fix for this is out. It's available in both our latest stable and preview releases!

**Comment by venkaa28** [comment]
@kalona the fix for this is out. It's available in both our latest stable and preview releases!
